import { GithubActionInputEntry, GithubActionInputType, HelmSubcommand } from "./models";


export const GITHUB_ACTIONS_INPUT_CONFIGURATION: GithubActionInputEntry[] = [
    {
        name: 'burst_limit',
        value: {
            description: 'client-side default throttling limit (default 100)',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.Number,
        },
    },
    {
        name: 'debug',
        value: {
            description: 'enable verbose output',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'kube_apiserver',
        value: {
            description: 'the address and the port for the Kubernetes API server',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'kube_as_group',
        value: {
            description: 'group to impersonate for the operation, this flag can be repeated to specify multiple groups.',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'kube_as_user',
        value: {
            description: 'username to impersonate for the operation',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'kube_ca_file',
        value: {
            description: 'the certificate authority file for the Kubernetes API server connection',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.File,
        },
    },
    {
        name: 'kube_context',
        value: {
            description: 'name of the kubeconfig context to use',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'kube_insecure_skip_tls_verify',
        value: {
            description: "if true, the Kubernetes API server's certificate will not be checked for validity. This will make your HTTPS connections insecure",
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'kube_token',
        value: {
            description: 'server name to use for Kubernetes API server certificate validation. If it is not provided, the hostname used to contact the server is used',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'kubeconfig',
        value: {
            description: 'path to the kubeconfig file',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.File,
        },
    },
    {
        name: 'namespace',
        value: {
            description: 'namespace scope for this request',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'registry_config',
        value: {
            description: "path to the registry config file (default '$HOME/.config/helm/registry/config.json')",
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.File,
        },
    },
    {
        name: 'repository_config',
        value: {
            description: "path to the file containing repository names and URLs (default '$HOME.config/helm/repositories.yaml')",
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.All],
            type: GithubActionInputType.File,
        },
    },
    {
        name: 'atomic',
        value: {
            description: 'if set, the installation process deletes the installation on failure. The --wait flag will be set automatically if --atomic is used',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'ca_file',
        value: {
            description: 'verify certificates of HTTPS-enabled servers using this CA bundle',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.File,
        },
    },
    {
        name: 'cert_file',
        value: {
            description: 'identify HTTPS client using this SSL certificate file',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.File,
        },
    },
    {
        name: 'cleanup_on_fail',
        value: {
            description: 'allow deletion of new resources created in this upgrade when upgrade fails',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'create_namespace',
        value: {
            description: 'create the release namespace if not present',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'dependency_update',
        value: {
            description: 'update dependencies if they are missing before installing the chart',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'description',
        value: {
            description: 'add a custom description',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'devel',
        value: {
            description: "use development versions, too. Equivalent to version '>0.0.0-0'. If --version is set, this is ignored",
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'disable_openapi_validation',
        value: {
            description: 'if set, the installation process will not validate rendered templates against the Kubernetes OpenAPI Schem',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'dry_run',
        value: {
            description: 'simulate an install',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'force',
        value: {
            description: 'force resource updates through a replacement strategy',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'generate_name',
        value: {
            description: 'generate the name (and omit the NAME parameter)',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'history_max',
        value: {
            description: 'limit the maximum number of revisions saved per release. Use 0 for no limit (default 10)',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'insecure_skip_tls_verify',
        value: {
            description: 'skip tls certificate checks for the chart download',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'install',
        value: {
            description: "if a release by this name doesn't already exist, run an install",
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'key_file',
        value: {
            description: 'identify HTTPS client using this SSL key file',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.File,
        },
    },
    {
        name: 'keyring',
        value: {
            description: 'location of public keys used for verification (default "$HOME/.gnupg/pubring.gpg")',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.File,
        },
    },
    {
        name: 'name_template',
        value: {
            description: 'specify template used to name the release',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'no_hooks',
        value: {
            description: 'prevent hooks from running during install',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'output',
        value: {
            description: 'prints the output in the specified format. Allowed values: table, json, yaml (default table)',
            required: true,
            default: 'table',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'pass_credentials',
        value: {
            description: 'pass credentials to all domains',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'password',
        value: {
            description: 'chart repository password where to locate the requested chart',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'ref',
        value: {
            description: 'reference to a chart repository (e.g. url, absolute or relative path)',
            required: true,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'release_name',
        value: {
            description: 'name of the helm release',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'render_subchart_notes',
        value: {
            description: 'if set, render subchart notes along with the parent',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'replace',
        value: {
            description: 're-use the given name, only if that name is a deleted release which remains in the history. This is unsafe in production',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'repo',
        value: {
            description: 'chart repository URL where to locate the requested chart',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'reset_values',
        value: {
            description: 'when upgrading, reset the values to the ones built into the chart',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'reuse_values',
        value: {
            description: "when upgrading, reuse the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' is specified, this is ignored",
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'set',
        value: {
            description: 'set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'set_file',
        value: {
            description: 'set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.File,
        },
    },
    {
        name: 'set_json',
        value: {
            description: 'set JSON values on the command line (can specify multiple or separate values with commas: key1=jsonval1,key2=jsonval2)',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'set_string',
        value: {
            description: 'set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'skip_crds',
        value: {
            description: 'if set, no CRDs will be installed when an upgrade is performed with install flag enabled. By default, CRDs are installed if not already present, when an upgrade is performed with install flag enabled',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'timeout',
        value: {
            description: 'time to wait for any individual Kubernetes operation (like Jobs for hooks) (default 5m0s)',
            required: true,
            default: '5m0s',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'username',
        value: {
            description: 'chart repository username where to locate the requested chart',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'values',
        value: {
            description: 'specify values in a YAML file or a URL (can specify multiple)',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String, // we handle this as a string since `File` doesn't currently support existing files
        },
    },
    {
        name: 'verify',
        value: {
            description: 'verify the package before using it',
            required: true,
            default: 'false',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    },
    {
        name: 'version',
        value: {
            description: 'chart version to install. If this is not specified, the latest version is installed.',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'wait',
        value: {
            description: 'if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as --timeout',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.String,
        },
    },
    {
        name: 'wait_for_jobs',
        value: {
            description: 'if set and --wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as --timeout',
            required: false,
            default: '',
            value: undefined,
            supported_subcommands: [HelmSubcommand.Upgrade, HelmSubcommand.Install],
            type: GithubActionInputType.Boolean,
        },
    }
]