name: Build and deploy

on:
  push:
    branches:
      - "develop"
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn test

  test_against_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: BlindfoldedSurgery/github-action-helm@develop
        with:
          subcommand: lint
          path: examples/default-helm-create-chart
          namespace: action-example
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
      - uses: BlindfoldedSurgery/github-action-helm@develop
        with:
          subcommand: install
          ref: examples/install-empty
          release_name: install-empty
          namespace: action-example
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
      - uses: BlindfoldedSurgery/github-action-helm@develop
        with:
          subcommand: upgrade
          ref: examples/install-empty
          release_name: install-empty
          namespace: action-example
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
      - uses: BlindfoldedSurgery/github-action-helm@develop
        with:
          subcommand: rollback
          release_name: install-empty
          namespace: action-example
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}

  cleanup:
    runs-on: ubuntu-latest
    needs: test_against_develop
    if: always()
    steps:
      - uses: BlindfoldedSurgery/github-action-helm@develop
        with:
          subcommand: uninstall
          namespace: action-example
          release_name: install-empty
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
