name: Build and deploy

on:
  push:
    branches:
      - "master"

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - run: yarn install
      - run: yarn test

  test_against_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: BlindfoldedSurgery/github-action-helm@master
        with:
          subcommand: install
          ref: examples/install-empty
          release_name: install-empty
          namespace: action-example
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
      - uses: BlindfoldedSurgery/github-action-helm@master
        with:
          subcommand: upgrade
          ref: examples/install-empty
          release_name: install-empty
          namespace: action-example
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
      - uses: BlindfoldedSurgery/github-action-helm@master
        with:
          subcommand: rollback
          release_name: install-empty
          namespace: action-example
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}

  cleanup:
    runs-on: ubuntu-latest
    needs: test_against_master
    if: always()
    steps:
      - uses: BlindfoldedSurgery/github-action-helm@master
        with:
          subcommand: uninstall
          namespace: action-example
          release_name: install-empty
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
